"""Recommender column

Revision ID: 163b49c050a2
Revises: 3737ae936621
Create Date: 2020-06-28 16:47:02.899018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163b49c050a2'
down_revision = '3737ae936621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('recommender', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'recommender')
    # ### end Alembic commands ###
